### PR TITLE
fix(asana): tags and projects spreadsheet selectors

### PR DESCRIPTION
**Pull request by askides**
Please remember the [Contributing Guidelines](https://github.com/toggl/track-extension/blob/master/docs/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

This PR fixes the Asana integrations by changing the selector in the spreadsheet for Projects and Tags.

As an extra, i added the prettier configuration of Toggl, used to keep the files up with code style. 

Go commit by commit, the last one is the fix.

## :bug: Recommendations for testing

Ensure that starting a TE from the Button will automatically resolve the Project and the Tags (if present) and if the 'Enable Automatic Tagging' is turned on.

closes: https://github.com/toggl/track-extension/issues/2321
closes: https://github.com/toggl/track-extension/issues/2317

### CODE REVIEW

**Comment by with-shrey** [comment]
Does this cover https://github.com/toggl/track-extension/issues/2317

(Can you link the issues closes # in description)

**Comment by with-shrey** [comment]
Can confirm it works for list

**Comment by askides** [comment]
> Can you also fix #2317
> 
> Also please tag the other issue as well in PR boby closes # (there's an integration that triggers intercom chat for support)

Didn't link because i didn't create the issue. Will create it.

**Comment by askides** [comment]
@with-shrey done.

**Review by with-shrey — APPROVED** [review]

**Pull request merged**
