### PR TITLE
feat (extension): handle Pomodoro break

### LINKED ISSUE #597: add brake handling to pomodoro tracker
It would be great if pomodoro tracker would have break handling

- after work phase we should count break phase (default time 5min)
- when break phase finish trigger alarm
- break phase can be editable in settings

### PR DESCRIPTION
**Pull request by bytrangle**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?
This PR creates an option for setting a Pomodoro break interval in the **Options** page.
On the front end, it adds a new input field in the Pomodoro tab, right under the *Pomodoro time interval in minutes**section. The inputs has a label **Short break interval in minutes** and lets user select from a list of recommended intervals: 0, 1, 2, 3, 4, 5. This list is a suggestion and users can also enter their own value.

There is validation to make sure that the value entered by users is an integer number and in case the users don't enter or select anything, the value is default to 0.

The back end then saves this value to browser storage under the key `pomodoroShortBreakInterval`. When the **Options** page is reloaded, the Pomodoro break interval value is retrieved from the corresponding key of browser storage and written to the input value. 

### Test the Pomodoro break interval setting

- Right click the extension icon and select Options to open the Options page.
- Click the Pomodoro tab and scroll down. You should see a new row under *Pomodoro timer interval in minutes* labeled **Short break duration in minutes**, followed by an input to set the interval value.
- Click the input, then select a number from the drop-down list, or type a valid integer value.
- Reload the Options page and you should see the value that you had entered in the input field.

https://user-images.githubusercontent.com/28924121/114856342-2e19af80-9e11-11eb-9e3c-7ce7e8ddc093.mp4

## :memo: Links to relevant issues or information

Resolves #597

### CODE REVIEW

**Comment by bytrangle** [comment]
**Update**:
Add functionalities to handle break:
- Keep track of Pomodoro sessions in the window object: 
  - is the current Pomodoro session *work* or *break*
  - is a break coming up next (`true` if current Pomodoro session is *work*)
  - pomodoro short break interval
- When a time entry has run its course, check if the current Pomodoro session value is *work* or *break*. If it is *work*, auto-start a time entry named **Pomodoro Break** that will run for an amount of time determined by the Pomodoro short break interval.

**Comment by alexandrebarbaruiva** [comment]
@bytrangle could you resolve the conflicts, please? Or maybe we could have chat on how to setup your branch locally so I can pickup your work

**Comment by bytrangle** [comment]
@alexandrebarbaruiva I'm not sure what I should do to resolve the conflict. Do I:
- update my branch with new commits from master
- resolve those conflicts
- then push the updated branch here

**Comment by alexandrebarbaruiva** [comment]
Is there any command that I can install the modified plugin on my chrome for testing? How do I setup the project locally?

**Comment by mwanago** [comment]
@bytrangle Hi. Any plans on merging this PR?

**Comment by mwanago** [comment]
@alexandrebarbaruiva I've noticed in the conflicts that many files were removed by @bytrangle. Do you maybe know why?

**Comment by mwanago** [comment]
@nunofmn Are there any plans to merge this functionality?

**Comment by alexandrebarbaruiva** [comment]
@mwanago I had no idea how to test it so never got further on this PR :cry: if you want to work together (or alone) to resolve conflicts and test this functionality, feel free to let me know!

**Comment by mwanago** [comment]
@alexandrebarbaruiva Looks like the part of `track-extension` that this PR was modifying is no longer open source.
https://toggl.com/blog/purposeful-open-source

"Recently, one of our development teams took full ownership of the browser extensions with plans to further improve them. As part of this change, we’ll be splitting the integrations from the heavier code of the browser extension.

The definitions will remain open source, which will make it easier for anyone to contribute with new or updated integrations. The main browser extension code will be closed, which will allow us to work on the extensions’ features more easily as it will allow us to share code with other projects."

**Comment by mwanagosos** [comment]
@nunofmn Could we get this merged to the closed-source repository?

**Comment by bytrangle** [comment]
> I wonder if there are updates on this.
You should ask the maintainer of this repo.

**Comment by DivineMK** [comment]
I'm not sure who is the current maintainer but shouldn't commenting here pump this up for all contributors?

**Comment by bytrangle** [comment]
> I'm not sure who is the current maintainer but shouldn't commenting here pump this up for all contributors?

I don't think so. I have closed this issue, so it's unlikely to get attention. And like the previous commenter said,  the main code of this extension is no longer open source, so this PR is meaningless anyway. If you still want to see this feature being materialized,  [Toggl](https://github.com/toggl) is the owner of this repo.

**Pull request closed without merging**
