### PR TITLE
fix(taiga): Fix taiga.io integration

### PR DESCRIPTION
**Pull request by EternallLight**
## :star2: What does this PR do?

Fixes integrations for taiga.io

## :bug: Recommendations for testing

Sign in to taiga.io with your github account and try to click around.

You're going to need to create both Kanban and Scrum projects.

Here's [the video](https://cln.sh/GsG56H) where to find the Toggl Button in both of them.

Check [where the button should show up](https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#taiga).

## :memo: Links to relevant issues or information

Closes https://github.com/toggl/track-extension/issues/1929

### CODE REVIEW

**Review by LulzAugusto — COMMENTED** [review]
I'm trying to test this but after cloning track-extension-core and pointing the track-extension to `"@toggl/track-extension": "toggl/track-extension#1929/taiga-fix",` and trying to run I get a webpack error, both from `yarn start` and `yarn build`. Any other ways of testing this?

**Comment by EternallLight** [comment]
@LulzAugusto here [is the recipe](https://github.com/toggl/track-extension/pull/2022#issuecomment-1005539338) how to test it now.

I really need to put it in the readme next week :)

**Review by LulzAugusto — APPROVED** [review]
Button was visible in all views 🙌

**Comment by EternallLight** [comment]
We've got a report that the button is interfering with the UI now.
It seems to happen with multiple-line titles or missing titles.

image
image
image

**Pull request merged**
