### PR TITLE
feat(github): Adds toggl-button to new project pane

### LINKED ISSUE #2090: Add integration support for new GitHub Projects issue pane.
### Describe the changes you'd like

Add support for new GitHub Projects issue pane.

### Relevant links or screenshots

When you click an issue name from the project board, the issue now opens in a pane from this view (without changing URL). Would it be possible to add a Toggl timer button to this view?

Projects [docs](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects).

image

### PR DESCRIPTION
**Pull request by Alissonsz**
## :star2: What does this PR do?
Adds toggl button to issues in github project page

## :bug: Recommendations for testing
- Go to github project page
- Click in any issue, it'll open a side pane
- Toggl button should show up

## :memo: Links to relevant issues or information
Closes #2090

### CODE REVIEW

**Comment by MarkBennett** [comment]
Going to enjoy getting to this from the project page. Thanks @Alissonsz! 🥳

**Comment by rhys-vdw** [comment]
Thank you @Alissonsz!

**Comment by Alissonsz** [comment]
The new version with this feature working is already on Firefox and must be up by tomorrow on chrome @MarkBennett @rhys-vdw 🙌

**Comment by rhys-vdw** [comment]
Doesn't seem to be working in 2.0.13, is that what c0b2f896c7e2518d2224b6e9edadd99a65308e36 is about/

**Comment by Alissonsz** [comment]
Yes @rhys-vdw, I made a mistake while deploying the version 2.0.13. The version 2.0.14 is now up on chrome and firefox store, the button should be working on that version!

**Pull request merged**
