### PR TITLE
Freedcamp integration

### PR DESCRIPTION
**Pull request by lewebsimple**
## :star2: What does this PR do?

Adds [Freedcamp](https://freedcamp.com) integration

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox.

### CODE REVIEW

**Comment by lise-toggl** [comment]
Hi @lewebsimple, thanks for your PR!

Here are a few things I noticed:
- The placement of the button needs a little tweaking. It would look more in-line if it were lower, and in front of the "Comments" icon (rather than behind) as that only appears on hover (see first row in pic):
image
- It would be good to also have the button on the Dashboard page:
image
- Maybe also on the Calendar page:
image

If you need help with these let me know!

**Comment by tcrammond** [comment]
Hey @lewebsimple 👋 are you intending to follow up the changes requested here, or do you need someone else to pick it up?

**Comment by lewebsimple** [comment]
@tcrammond If you're interested to work on this, go ahead !

**Comment by with-shrey** [comment]
Closed in favour of #2284

**Pull request closed without merging**
