### PR TITLE
fix(jira): Fix button not showing up

### LINKED ISSUE #2243: Button not showing up for jira
* **OS version**: 
* **Browser version**: 
* **Extension version**: 

#### Relevant integration (if any):
Jira

### 🐛 Describe the bug
Button not showing up

### Other details or context
Thread: https://toggl.slack.com/archives/C043ZPZQ2JC/p1696322949403979

### PR DESCRIPTION
**Pull request by Alissonsz**
## :star2: What does this PR do?
- [fix(jira): Fix button not showing up](https://github.com/toggl/track-extension/commit/42b792a8d96e5d467dda0eb06f8fcf285d41b9e2)

## :bug: Recommendations for testing
- Check if the button is now showing up again
All changes should be tested across Chrome and Firefox.

## :memo: Links to relevant issues or information
Closes #2243

### CODE REVIEW

**Comment by kburakf** [comment]
hi @Alissonsz

is this about fixing the situation where I can't see the button in jira?

**Comment by Alissonsz** [comment]
Hi @kburakf, yes!!

**Comment by Spurlos** [comment]
We need this in a release as soon as possible! I felt like I have lost a hand today, without the toggl shortcut near my Jira tickets :)

**Review by rafaelbubach — APPROVED** [review]
lgtm

**Pull request merged**
