### PR TITLE
refactor(content): Update scripts/content to use $$ and $ helpers

### PR DESCRIPTION
**Pull request by glensc**
## :star2: What does this PR do?

Replace code to use `$$` and `$` helpers in `src/content`.

## :bug: Recommendations for testing

I manually made all changes, so the typos are very unlikely to be present.

## :memo: Links to relevant issues or information

Requires https://github.com/toggl/toggl-button/pull/1879 to be merged first

### CODE REVIEW

**Comment by glensc** [comment]
https://github.com/toggl/toggl-button/pull/1879 was merged, removing Draft status

**Comment by glensc** [comment]
Rebased and removed changes to conflicting files:
- src/scripts/content/atlassian.js
- src/scripts/content/todoist.js

ping @rylek90, I would hate to rebase and resolve conflicts again.

**Comment by rylek90** [comment]
Hey @glensc, thank you for your contribution. 

Unfortunately we've discussed your changes with a team and unfortunately we cannot accept them at this moment. 

Although #1879 was really nice addition to our code base and I'm sure this PR is as well, we simply cannot spend time on testing 50 integrations and ensure nothing is broken. Maybe at some point of time we will revisit it, rebase by ourselves, deeply test and merge, but not today, not even in the nearest time. 

We're still open for bugfixes and new integrations but while this PR is indeed nice stylistic addition it doesn't seem to be needed now.

We're deeply sorry for inconvenience. Thank you for your time and let's hope we'll have time to revisit it in the future. :pray:

**Comment by glensc** [comment]
@rylek90 perhaps you list integrations that are you able to test and I split those integrations to a separate PR. and in that case, each integration a separate PR or multiple in one (using task-list maybe)?

**Pull request closed without merging**
